vit:
  r: 32
  lora_alpha: 32
  target_modules: ['query', 'key', 'value', 'output.dense']
  lora_dropout: 0.1
  bias: 'all'
bert:
  r: 32
  lora_alpha: 32
  target_modules: ['query', 'key', 'value', 'output.dense']
  lora_dropout: 0.1
  bias: 'all'
  task_type: 'FEATURE_EXTRACTION'
